# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16S4fxqVBfQUqYFPYoUYLLOS0qu-l_L2M
"""

pip install ultralytics

import ultralytics
print(ultralytics.__version__)

from ultralytics import YOLO

# Load a pretrained YOLO model
model = YOLO('yolov8n.pt')

results = model.predict('/content/bus.jpg')

from PIL import Image

for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    display(im)